[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[dependencies]
solver = { path = "../solver" }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "benchmarks"
harness = false